const TEAMS={"North Team": ["Senan Alkawamleh", "Carlo Mendez", "Ummer Mohd", "Mohamed Alanazi", "Jamjom", "Faizal", "Momen Hasan"], "Central Team": ["Muhanned Hassan", "Sheikoli Mydeen", "Mogtaba Ahmad", "Muaaz Hezam", "Ahmed Nasser", "Khalid Erhaim"], "East Team": ["Moataz Tammam", "Nayyar Abbas", "Marwan Elgurshi", "Elmer Salcedo", "Hassan Alkhabbaz", "Musa Elsiddig", "Nhec Inao"], "South Team": ["Abdullah Gomaa", "El-Sayed Eissa", "Mohammed Arif", "Abdulrahim Bawazeer", "Hussain Al Zeidan", "Amri Alkhidder", "Arsalan khan"], "Al-Kharj Team": ["Devid Gromio", "Ibrahim Qaysi"], "Hail Team": ["Ieyad Khany", "Ahmed Tawhal"], "Qassim Team": ["Mamdouh Saibi", "Manzul Kasim", "Rehmatullah", "Joel Malicdem", "Yousif Yassen", "Tariq Elobaid"], "Dawadmi Team": ["Sherif Wagdi"]};
const A={name:["ce name","employee name","employee","engineer name","engineer","name"],code:["ce code","employee code","emp code","engineer code","code"],date:["date","activity date","call date","week start","completed date","close date"],slm:["7 day slm revisit","7 day revisit","slm revisit","slm"],ccpdw:["ccpdw"],retrip:["re-trip","retrip","re trip"],sla:["sla response","response sla","sla"],util:["utilization","utilisation"],fund:["call fundamentals","fundamentals"],closed:["closed srs","closed sr","closed service requests","closed"],opp:["response opp","response opportunity","response opportunities"]};
const KEY="CE_PERF_V4";
const state={records:JSON.parse(localStorage.getItem(KEY)||"[]"),page:"dashboard",team:"ALL",month:"ALL",week:"ALL",q:""};
const $=id=>document.getElementById(id);
const norm=x=>String(x??"").toUpperCase().trim().replace(/[^A-Z0-9]+/g," ").replace(/\s+/g," ").trim();
const comp=x=>norm(x).replace(/\s/g,"");
function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function col(h,aa){let n=h.map(norm);for(let a of aa){let i=n.indexOf(norm(a));if(i>=0)return i}for(let a of aa){let i=n.findIndex(x=>x.includes(norm(a)));if(i>=0)return i}return -1}
function num(v){if(v===""||v==null)return null;let s=String(v).replace(/,/g,""),p=s.includes("%");s=s.replace("%","");let n=parseFloat(s);return Number.isFinite(n)?p?n/100:n:null}
function cname(v){let n=norm(v);for(let m of Object.values(TEAMS)){let e=m.find(x=>norm(x)==n);if(e)return e}
let a={"NHEC NJ INAO":"Nhec Inao","NHEC NJ A INAO":"Nhec Inao","MARWAN ELGORSCH":"Marwan Elgurshi","MARWAN ELGORSH":"Marwan Elgurshi","HASSAN ALKABBAZ":"Hassan Alkhabbaz"};return a[n]||String(v||"").trim()}
function getTeam(n){n=cname(n);for(let[t,m]of Object.entries(TEAMS))if(m.some(x=>norm(x)==norm(n)))return t;return"Unassigned"}
function dt(v){if(v instanceof Date&&!isNaN(v))return v;if(typeof v==="number"&&v>20000)return new Date(Date.UTC(1899,11,30)+v*86400000);let d=new Date(v);return isNaN(d)?null:d}
function weekInfo(d){if(!d)return{key:"Unknown",label:"Unknown",month:"Unknown"};d=new Date(d.getFullYear(),d.getMonth(),d.getDate());let first=new Date(d.getFullYear(),d.getMonth(),1),offset=(first.getDay()+6)%7,w=Math.floor((d.getDate()+offset-1)/7)+1,start=new Date(d.getFullYear(),d.getMonth(),1+(w-1)*7-offset);if(start.getMonth()!=d.getMonth())start=new Date(d.getFullYear(),d.getMonth(),1);let end=new Date(start);end.setDate(start.getDate()+6);let last=new Date(d.getFullYear(),d.getMonth()+1,0);if(end>last)end=last;return{key:d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-W"+w,label:"Week "+w+" ("+start.toLocaleDateString()+" - "+end.toLocaleDateString()+")",month:d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")}}
function parse(rows,h){let i={};for(let k in A)i[k]=col(h,A[k]);if(i.name<0&&i.code<0)throw Error("CE Name or CE Code column not found.");
return rows.flatMap((r,z)=>{let raw=i.name>=0?r[i.name]:"",code=i.code>=0?r[i.code]:"";if(String(raw).trim()===""&&String(code).trim()==="")return[];let n=cname(raw||code),d=i.date>=0?dt(r[i.date]):null,w=weekInfo(d);return[{id:Date.now()+"-"+z+"-"+Math.random(),name:n,code:String(code||"").trim(),team:getTeam(n),date:d?d.toISOString().slice(0,10):"",week:w.key,weekLabel:w.label,month:w.month,slm:i.slm>=0?num(r[i.slm]):null,ccpdw:i.ccpdw>=0?num(r[i.ccpdw]):null,retrip:i.retrip>=0?num(r[i.retrip]):null,sla:i.sla>=0?num(r[i.sla]):null,util:i.util>=0?num(r[i.util]):null,fund:i.fund>=0?num(r[i.fund]):null,closed:i.closed>=0?num(r[i.closed]):null,opp:i.opp>=0?num(r[i.opp]):null}]})}
function score(v,t,d){if(v==null)return null;if(t===0)return d==="low"?(v<=0?100:Math.max(0,100-v*100)):100;if(d==="high")return Math.min(100,v/t*100);return v<=t?100:Math.max(0,t/v*100)}
function pct(rows,k,d){let a=rows.filter(x=>x[k]!=null),v=a.map(x=>+x[k]),m=new Map();a.forEach(x=>{let b=d==="high"?v.filter(z=>z>x[k]).length:v.filter(z=>z<x[k]).length;m.set(x.id,100*(v.length-b-1)/Math.max(1,v.length-1))});return m}
function calc(rows){let c=pct(rows,"closed","high"),o=pct(rows,"opp","low");return rows.map(x=>{let s=[],m={};for(let k of["slm","ccpdw","retrip","sla","util","fund"]){let t={slm:0,ccpdw:4,retrip:0,sla:1,util:1,fund:1}[k],d=["ccpdw","sla","util","fund"].includes(k)?"high":"low";m[k]=score(x[k],t,d);if(m[k]!=null)s.push(m[k])}m.closed=c.get(x.id)??null;m.opp=o.get(x.id)??null;if(m.closed!=null)s.push(m.closed);if(m.opp!=null)s.push(m.opp);return{...x,score:s.length?s.reduce((a,b)=>a+b,0)/s.length:null}})}
function filtered(){let r=state.records;if(state.team!="ALL")r=r.filter(x=>x.team==state.team);if(state.month!="ALL")r=r.filter(x=>x.month==state.month);if(state.week!="ALL")r=r.filter(x=>x.week==state.week);let q=norm(state.q),cq=comp(state.q);if(q)r=r.filter(x=>norm(x.name).includes(q)||norm(x.code).includes(q)||comp(x.name).includes(cq)||comp(x.code).includes(cq));return r}
function ranked(r){return calc(r).sort((a,b)=>(b.score??-1)-(a.score??-1)).map((x,i)=>({...x,rank:i+1}))}
function pv(v){return v==null?"—":(v*100).toFixed(1)+"%"}function nv(v){return v==null?"—":Number(v).toLocaleString(undefined,{maximumFractionDigits:2})}
function badge(s){return s==null?'<span class="badge none">No Data</span>':s>=85?'<span class="badge good">Outstanding</span>':s>=70?'<span class="badge good">Strong</span>':s>=55?'<span class="badge mid">Developing</span>':'<span class="badge bad">Needs Improvement</span>'}
function table(rows){let r=ranked(rows);if(!r.length)return'<div class="empty">No records found.</div>';return'<div class="wrap"><table><thead><tr><th>Rank</th><th>CE Name</th><th>CE Code</th><th>Team</th><th>Score</th><th>Status</th><th>7 Day SLM</th><th>CCPDW</th><th>Re-trip</th><th>SLA</th><th>Util.</th><th>Fund.</th><th>Closed SRs</th><th>Response Opp</th></tr></thead><tbody>'+r.map(x=>`<tr><td><b>#${x.rank}</b></td><td><b>${esc(x.name)}</b></td><td>${esc(x.code)}</td><td>${esc(x.team)}</td><td><b>${x.score==null?"—":x.score.toFixed(1)}</b></td><td>${badge(x.score)}</td><td>${pv(x.slm)}</td><td>${nv(x.ccpdw)}</td><td>${pv(x.retrip)}</td><td>${pv(x.sla)}</td><td>${pv(x.util)}</td><td>${pv(x.fund)}</td><td>${nv(x.closed)}</td><td>${nv(x.opp)}</td></tr>`).join("")+"</tbody></table></div>"}
function setFilters(){teamFilter.innerHTML='<option value="ALL">All Teams</option>'+Object.keys(TEAMS).map(t=>`<option>${esc(t)}</option>`).join("");teamFilter.value=state.team;let ms=[...new Set(state.records.map(x=>x.month))].filter(Boolean).sort().reverse();monthFilter.innerHTML='<option value="ALL">All Months</option>'+ms.map(x=>`<option>${x}</option>`).join("");monthFilter.value=state.month;let ws=[...new Set(state.records.filter(x=>state.month=="ALL"||x.month==state.month).map(x=>x.week))].filter(Boolean).sort().reverse();weekFilter.innerHTML='<option value="ALL">All Weeks</option>'+ws.map(x=>`<option value="${x}">${x}</option>`).join("");weekFilter.value=state.week;search.value=state.q}
function dashboard(){let r=ranked(filtered()),s=r.map(x=>x.score).filter(x=>x!=null),a=s.length?s.reduce((p,q)=>p+q,0)/s.length:null;app.innerHTML=`<div class="cards"><div class="card">Records<b>${r.length}</b></div><div class="card">Average Score<b>${a==null?"—":a.toFixed(1)}</b></div><div class="card">Top Performer<b>${esc(r[0]?.name||"—")}</b></div><div class="card">Months<b>${new Set(state.records.map(x=>x.month)).size}</b></div><div class="card">Employees<b>38</b></div></div><div class="panel"><h2>Top Ranking</h2>${table(r.slice(0,10))}</div>`}
function ranking(){app.innerHTML='<div class="panel"><h2>Top Ranking</h2><div class="notice">The Print/PDF and Excel buttons export the currently filtered ranking.</div>'+table(filtered())+'</div>'}
function weekly(){let r=filtered(),groups=[...new Set(r.map(x=>x.week))].sort().reverse();app.innerHTML=groups.map(w=>`<div class="panel"><h2>${esc(r.find(x=>x.week==w)?.weekLabel||w)}</h2><div class="small">Month: ${esc(r.find(x=>x.week==w)?.month||"")}</div>${table(r.filter(x=>x.week==w))}</div>`).join("")||'<div class="empty">No weekly data.</div>'}
function monthly(){let r=filtered(),groups=[...new Set(r.map(x=>x.month))].sort().reverse();app.innerHTML=groups.map(m=>`<div class="panel"><h2>Monthly Summary: ${esc(m)}</h2><div class="notice">This summary combines all weekly uploads belonging to this month.</div>${table(r.filter(x=>x.month==m))}</div>`).join("")||'<div class="empty">No monthly data.</div>'}
function employees(){let names=Object.values(TEAMS).flat(),r=filtered(),allrank=ranked(r);app.innerHTML='<div class="panel"><h2>All Employees</h2><div class="notice">All 38 employees are always displayed. Employees without uploaded records are marked No Data.</div><div class="wrap"><table><thead><tr><th>Rank</th><th>Employee</th><th>Team</th><th>CE Code</th><th>Records</th><th>Average Score</th><th>Status</th></tr></thead><tbody>'+names.map(n=>{let x=r.filter(z=>norm(z.name)==norm(n)),c=calc(x),s=c.map(z=>z.score).filter(v=>v!=null),a=s.length?s.reduce((p,q)=>p+q,0)/s.length:null,rank=allrank.findIndex(z=>norm(z.name)==norm(n));return`<tr><td>${a==null?"—":"#"+(rank+1)}</td><td><b>${esc(n)}</b></td><td>${esc(getTeam(n))}</td><td>${esc(x[0]?.code||"")}</td><td>${x.length}</td><td>${a==null?"—":a.toFixed(1)}</td><td>${badge(a)}</td></tr>`}).join("")+'</tbody></table></div></div>'}
function teams(){app.innerHTML='<div class="teams">'+Object.entries(TEAMS).map(([t,m])=>`<div class="team"><h3>${esc(t)} (${m.length})</h3><ul>${m.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div>`).join("")+'</div>'}
function rules(){app.innerHTML='<div class="panel"><h2>Performance Rules</h2><table><tr><th>Metric</th><th>Target</th><th>Direction</th></tr><tr><td>7 Day SLM Revisit</td><td>0%</td><td>Lower is better</td></tr><tr><td>CCPDW</td><td>4</td><td>Higher is better</td></tr><tr><td>Re-trip</td><td>0%</td><td>Lower is better</td></tr><tr><td>SLA Response</td><td>100%</td><td>Higher is better</td></tr><tr><td>Utilization</td><td>100%</td><td>Higher is better</td></tr><tr><td>Call Fundamentals</td><td>100%</td><td>Higher is better</td></tr><tr><td>Closed SRs</td><td>Higher is better</td><td>Percentile</td></tr><tr><td>Response Opp</td><td>Lower is better</td><td>Percentile</td></tr></table></div>'}
function render(){setFilters();let titles={dashboard:["Dashboard","Weekly and monthly performance"],ranking:["Top Ranking","Current filtered ranking"],weekly:["Weekly Tracking","Separate 7-day upload periods"],monthly:["Monthly Summary","Combined weekly records by month"],employees:["All Employees","Complete employee list including no-data employees"],teams:["Teams","Employee master database"],rules:["Performance Rules","Configured scoring rules"]};title.textContent=titles[state.page][0];sub.textContent=titles[state.page][1];document.querySelectorAll("aside button[data-page]").forEach(b=>b.classList.toggle("active",b.dataset.page==state.page));if(state.page=="dashboard")dashboard();else if(state.page=="ranking")ranking();else if(state.page=="weekly")weekly();else if(state.page=="monthly")monthly();else if(state.page=="employees")employees();else if(state.page=="teams")teams();else rules()}
document.querySelectorAll("aside button[data-page]").forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});
teamFilter.onchange=()=>{state.team=teamFilter.value;render()};monthFilter.onchange=()=>{state.month=monthFilter.value;state.week="ALL";render()};weekFilter.onchange=()=>{state.week=weekFilter.value;render()};search.oninput=()=>{state.q=search.value;render()};clear.onclick=()=>{state.team="ALL";state.month="ALL";state.week="ALL";state.q="";render()};
uploadBtn.onclick=()=>modal.classList.add("show");close.onclick=()=>modal.classList.remove("show");
file.onchange=async()=>{let f=file.files[0];if(!f)return;msg.textContent="Reading Excel...";try{let wb=XLSX.read(await f.arrayBuffer(),{type:"array",cellDates:true}),sh=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(sh,{header:1,defval:"",raw:true}),newRows=parse(rows.slice(1),rows[0]);state.records.push(...newRows);localStorage.setItem(KEY,JSON.stringify(state.records));msg.textContent="Imported "+newRows.length+" records.";setTimeout(()=>{modal.classList.remove("show");state.page="weekly";render()},700)}catch(e){msg.textContent="ERROR: "+e.message}};
function exportExcel(){let r=ranked(filtered());if(!r.length)return alert("No data to export.");let data=r.map(x=>({Rank:x.rank,"CE Name":x.name,"CE Code":x.code,Team:x.team,Week:x.week,Month:x.month,"Performance Score":x.score==null?"":+x.score.toFixed(2),"7 Day SLM Revisit":x.slm,"CCPDW":x.ccpdw,"Re-trip":x.retrip,"SLA Response":x.sla,"Utilization":x.util,"Call Fundamentals":x.fund,"Closed SRs":x.closed,"Response Opp":x.opp}));let ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Ranking");XLSX.writeFile(wb,"CE_Performance_Ranking.xlsx")}
printBtn.onclick=()=>{if(!filtered().length)return alert("No data to print.");window.print()};excelBtn.onclick=exportExcel;render();
